#pragma once

#define CTSPACES_VERSION_NUMBER 6, 3, 0, 0
#define CTSPACES_VERSION_TEXT "6.3.0.0"
#define CTSPACES_VERSION_WTEXT L"6.3.0.0"
#define CTSPACES_DISPLAY_VERSION_TEXT "6.3"
#define CTSPACES_DISPLAY_VERSION_WTEXT L"6.3"
#define CTSPACES_ABOUT_TEXT "ctSpaces, Version 6.3"
