#pragma once

#define CTSPACES_VERSION_NUMBER 5, 3, 0, 10
#define CTSPACES_VERSION_TEXT "5.3.0.10"
#define CTSPACES_VERSION_WTEXT L"5.3.0.10"
#define CTSPACES_DISPLAY_VERSION_TEXT "5.3"
#define CTSPACES_DISPLAY_VERSION_WTEXT L"5.3"
#define CTSPACES_ABOUT_TEXT "ctSpaces, Version 5.3"
