#pragma once

#define CTSPACES_VERSION_NUMBER 6, 0, 4, 0
#define CTSPACES_VERSION_TEXT "6.0.4.0"
#define CTSPACES_VERSION_WTEXT L"6.0.4.0"
#define CTSPACES_DISPLAY_VERSION_TEXT "6.0"
#define CTSPACES_DISPLAY_VERSION_WTEXT L"6.0"
#define CTSPACES_ABOUT_TEXT "ctSpaces, Version 6.0"
